version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: botanalitic-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: botanalitic
      POSTGRES_PASSWORD: botanalitic
      POSTGRES_DB: botanalitic
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
